// Decompiled by Jad v1.5.8e. Copyright 2001 Pavel Kouznetsov.
// Jad home page: http://www.geocities.com/kpdus/jad.html
// Decompiler options: packimports(3) fieldsfirst lnc 
// Source File Name:   StandardNames.java

package com.icl.saxon.style;

import com.icl.saxon.om.NamePool;

public class StandardNames
{

            public NamePool pool;
            public int XML_SPACE;
            public int XML_LANG;
            public int XSL_APPLY_IMPORTS;
            public int XSL_APPLY_TEMPLATES;
            public int XSL_ATTRIBUTE;
            public int XSL_ATTRIBUTE_SET;
            public int XSL_CALL_TEMPLATE;
            public int XSL_CHOOSE;
            public int XSL_COMMENT;
            public int XSL_COPY;
            public int XSL_COPY_OF;
            public int XSL_DECIMAL_FORMAT;
            public int XSL_DOCUMENT;
            public int XSL_ELEMENT;
            public int XSL_FALLBACK;
            public int XSL_FOR_EACH;
            public int XSL_IF;
            public int XSL_IMPORT;
            public int XSL_INCLUDE;
            public int XSL_KEY;
            public int XSL_MESSAGE;
            public int XSL_NUMBER;
            public int XSL_NAMESPACE_ALIAS;
            public int XSL_OTHERWISE;
            public int XSL_OUTPUT;
            public int XSL_PARAM;
            public int XSL_PRESERVE_SPACE;
            public int XSL_PROCESSING_INSTRUCTION;
            public int XSL_SCRIPT;
            public int XSL_SORT;
            public int XSL_STRIP_SPACE;
            public int XSL_STYLESHEET;
            public int XSL_TEMPLATE;
            public int XSL_TEXT;
            public int XSL_TRANSFORM;
            public int XSL_VALUE_OF;
            public int XSL_VARIABLE;
            public int XSL_WITH_PARAM;
            public int XSL_WHEN;
            public int SAXON_ASSIGN;
            public int SAXON_DOCTYPE;
            public int SAXON_ENTITY_REF;
            public int SAXON_FUNCTION;
            public int SAXON_GROUP;
            public int SAXON_HANDLER;
            public int SAXON_ITEM;
            public int SAXON_OUTPUT;
            public int SAXON_PREVIEW;
            public int SAXON_SCRIPT;
            public int SAXON_RETURN;
            public int SAXON_WHILE;
            public int EXSLT_FUNC_FUNCTION;
            public int EXSLT_FUNC_RESULT;
            public int ARCHIVE;
            public int CASE_ORDER;
            public int CDATA_SECTION_ELEMENTS;
            public int COUNT;
            public int DATA_TYPE;
            public int DECIMAL_SEPARATOR;
            public int DIGIT;
            public int DISABLE_OUTPUT_ESCAPING;
            public int DOCTYPE_PUBLIC;
            public int DOCTYPE_SYSTEM;
            public int ELEMENTS;
            public int ENCODING;
            public int EXCLUDE_RESULT_PREFIXES;
            public int EXTENSION_ELEMENT_PREFIXES;
            public int FILE;
            public int FORMAT;
            public int FROM;
            public int GROUP_BY;
            public int GROUPING_SEPARATOR;
            public int GROUPING_SIZE;
            public int HANDLER;
            public int HREF;
            public int ID;
            public int IMPLEMENTS_PREFIX;
            public int INDENT;
            public int INFINITY;
            public int LANG;
            public int LANGUAGE;
            public int LETTER_VALUE;
            public int LEVEL;
            public int MATCH;
            public int MEDIA_TYPE;
            public int METHOD;
            public int MINUS_SIGN;
            public int MODE;
            public int NAME;
            public int NAMESPACE;
            public int NAN;
            public int OMIT_XML_DECLARATION;
            public int ORDER;
            public int RESULT_PREFIX;
            public int PATTERN_SEPARATOR;
            public int PERCENT;
            public int PER_MILLE;
            public int PRIORITY;
            public int SELECT;
            public int SRC;
            public int STANDALONE;
            public int STYLESHEET_PREFIX;
            public int TERMINATE;
            public int TEST;
            public int USE;
            public int USE_ATTRIBUTE_SETS;
            public int USER_DATA;
            public int VALUE;
            public int VERSION;
            public int ZERO_DIGIT;
            public int SAXON_ALLOW_AVT;
            public int SAXON_ASSIGNABLE;
            public int SAXON_DISABLE_OUTPUT_ESCAPING;
            public int SAXON_OMIT_META_TAG;
            public int SAXON_CHARACTER_REPRESENTATION;
            public int SAXON_INDENT_SPACES;
            public int SAXON_NEXT_IN_CHAIN;
            public int SAXON_REQUIRE_WELL_FORMED;
            public int XSL_EXCLUDE_RESULT_PREFIXES;
            public int XSL_EXTENSION_ELEMENT_PREFIXES;
            public int XSL_USE_ATTRIBUTE_SETS;
            public int XSL_VERSION;

            public StandardNames(NamePool namepool)
            {
/* 144*/        pool = namepool;
            }

            public void allocateNames()
            {
/* 149*/        XML_SPACE = 0xfffff & pool.allocate("xml", "http://www.w3.org/XML/1998/namespace", "space");
/* 150*/        XML_LANG = 0xfffff & pool.allocate("xml", "http://www.w3.org/XML/1998/namespace", "lang");
/* 152*/        XSL_APPLY_IMPORTS = 0xfffff & pool.allocate("xsl", "http://www.w3.org/1999/XSL/Transform", "apply-imports");
/* 153*/        XSL_APPLY_TEMPLATES = 0xfffff & pool.allocate("xsl", "http://www.w3.org/1999/XSL/Transform", "apply-templates");
/* 154*/        XSL_ATTRIBUTE = 0xfffff & pool.allocate("xsl", "http://www.w3.org/1999/XSL/Transform", "attribute");
/* 155*/        XSL_ATTRIBUTE_SET = 0xfffff & pool.allocate("xsl", "http://www.w3.org/1999/XSL/Transform", "attribute-set");
/* 156*/        XSL_CALL_TEMPLATE = 0xfffff & pool.allocate("xsl", "http://www.w3.org/1999/XSL/Transform", "call-template");
/* 157*/        XSL_CHOOSE = 0xfffff & pool.allocate("xsl", "http://www.w3.org/1999/XSL/Transform", "choose");
/* 158*/        XSL_COMMENT = 0xfffff & pool.allocate("xsl", "http://www.w3.org/1999/XSL/Transform", "comment");
/* 159*/        XSL_COPY = 0xfffff & pool.allocate("xsl", "http://www.w3.org/1999/XSL/Transform", "copy");
/* 160*/        XSL_COPY_OF = 0xfffff & pool.allocate("xsl", "http://www.w3.org/1999/XSL/Transform", "copy-of");
/* 161*/        XSL_DECIMAL_FORMAT = 0xfffff & pool.allocate("xsl", "http://www.w3.org/1999/XSL/Transform", "decimal-format");
/* 162*/        XSL_DOCUMENT = 0xfffff & pool.allocate("xsl", "http://www.w3.org/1999/XSL/Transform", "document");
/* 163*/        XSL_ELEMENT = 0xfffff & pool.allocate("xsl", "http://www.w3.org/1999/XSL/Transform", "element");
/* 164*/        XSL_FALLBACK = 0xfffff & pool.allocate("xsl", "http://www.w3.org/1999/XSL/Transform", "fallback");
/* 165*/        XSL_FOR_EACH = 0xfffff & pool.allocate("xsl", "http://www.w3.org/1999/XSL/Transform", "for-each");
/* 166*/        XSL_IF = 0xfffff & pool.allocate("xsl", "http://www.w3.org/1999/XSL/Transform", "if");
/* 167*/        XSL_IMPORT = 0xfffff & pool.allocate("xsl", "http://www.w3.org/1999/XSL/Transform", "import");
/* 168*/        XSL_INCLUDE = 0xfffff & pool.allocate("xsl", "http://www.w3.org/1999/XSL/Transform", "include");
/* 169*/        XSL_KEY = 0xfffff & pool.allocate("xsl", "http://www.w3.org/1999/XSL/Transform", "key");
/* 170*/        XSL_MESSAGE = 0xfffff & pool.allocate("xsl", "http://www.w3.org/1999/XSL/Transform", "message");
/* 171*/        XSL_NUMBER = 0xfffff & pool.allocate("xsl", "http://www.w3.org/1999/XSL/Transform", "number");
/* 172*/        XSL_NAMESPACE_ALIAS = 0xfffff & pool.allocate("xsl", "http://www.w3.org/1999/XSL/Transform", "namespace-alias");
/* 173*/        XSL_OTHERWISE = 0xfffff & pool.allocate("xsl", "http://www.w3.org/1999/XSL/Transform", "otherwise");
/* 174*/        XSL_OUTPUT = 0xfffff & pool.allocate("xsl", "http://www.w3.org/1999/XSL/Transform", "output");
/* 175*/        XSL_PARAM = 0xfffff & pool.allocate("xsl", "http://www.w3.org/1999/XSL/Transform", "param");
/* 176*/        XSL_PRESERVE_SPACE = 0xfffff & pool.allocate("xsl", "http://www.w3.org/1999/XSL/Transform", "preserve-space");
/* 177*/        XSL_PROCESSING_INSTRUCTION = 0xfffff & pool.allocate("xsl", "http://www.w3.org/1999/XSL/Transform", "processing-instruction");
/* 179*/        XSL_SCRIPT = 0xfffff & pool.allocate("xsl", "http://www.w3.org/1999/XSL/Transform", "script");
/* 180*/        XSL_SORT = 0xfffff & pool.allocate("xsl", "http://www.w3.org/1999/XSL/Transform", "sort");
/* 181*/        XSL_STRIP_SPACE = 0xfffff & pool.allocate("xsl", "http://www.w3.org/1999/XSL/Transform", "strip-space");
/* 182*/        XSL_STYLESHEET = 0xfffff & pool.allocate("xsl", "http://www.w3.org/1999/XSL/Transform", "stylesheet");
/* 183*/        XSL_TEMPLATE = 0xfffff & pool.allocate("xsl", "http://www.w3.org/1999/XSL/Transform", "template");
/* 184*/        XSL_TEXT = 0xfffff & pool.allocate("xsl", "http://www.w3.org/1999/XSL/Transform", "text");
/* 185*/        XSL_TRANSFORM = 0xfffff & pool.allocate("xsl", "http://www.w3.org/1999/XSL/Transform", "transform");
/* 186*/        XSL_VALUE_OF = 0xfffff & pool.allocate("xsl", "http://www.w3.org/1999/XSL/Transform", "value-of");
/* 187*/        XSL_VARIABLE = 0xfffff & pool.allocate("xsl", "http://www.w3.org/1999/XSL/Transform", "variable");
/* 188*/        XSL_WITH_PARAM = 0xfffff & pool.allocate("xsl", "http://www.w3.org/1999/XSL/Transform", "with-param");
/* 189*/        XSL_WHEN = 0xfffff & pool.allocate("xsl", "http://www.w3.org/1999/XSL/Transform", "when");
/* 191*/        SAXON_ASSIGN = 0xfffff & pool.allocate("saxon", "http://icl.com/saxon", "assign");
/* 192*/        SAXON_DOCTYPE = 0xfffff & pool.allocate("saxon", "http://icl.com/saxon", "doctype");
/* 193*/        SAXON_ENTITY_REF = 0xfffff & pool.allocate("saxon", "http://icl.com/saxon", "entity-ref");
/* 194*/        SAXON_FUNCTION = 0xfffff & pool.allocate("saxon", "http://icl.com/saxon", "function");
/* 195*/        SAXON_GROUP = 0xfffff & pool.allocate("saxon", "http://icl.com/saxon", "group");
/* 196*/        SAXON_HANDLER = 0xfffff & pool.allocate("saxon", "http://icl.com/saxon", "handler");
/* 197*/        SAXON_ITEM = 0xfffff & pool.allocate("saxon", "http://icl.com/saxon", "item");
/* 198*/        SAXON_OUTPUT = 0xfffff & pool.allocate("saxon", "http://icl.com/saxon", "output");
/* 199*/        SAXON_PREVIEW = 0xfffff & pool.allocate("saxon", "http://icl.com/saxon", "preview");
/* 200*/        SAXON_SCRIPT = 0xfffff & pool.allocate("saxon", "http://icl.com/saxon", "script");
/* 201*/        SAXON_RETURN = 0xfffff & pool.allocate("saxon", "http://icl.com/saxon", "return");
/* 202*/        SAXON_WHILE = 0xfffff & pool.allocate("saxon", "http://icl.com/saxon", "while");
/* 204*/        EXSLT_FUNC_FUNCTION = 0xfffff & pool.allocate("func", "http://exslt.org/functions", "function");
/* 205*/        EXSLT_FUNC_RESULT = 0xfffff & pool.allocate("func", "http://exslt.org/functions", "result");
/* 208*/        ARCHIVE = 0xfffff & pool.allocate("", "", "archive");
/* 209*/        CASE_ORDER = 0xfffff & pool.allocate("", "", "case-order");
/* 210*/        CDATA_SECTION_ELEMENTS = 0xfffff & pool.allocate("", "", "cdata-section-elements");
/* 211*/        COUNT = 0xfffff & pool.allocate("", "", "count");
/* 212*/        DATA_TYPE = 0xfffff & pool.allocate("", "", "data-type");
/* 213*/        DECIMAL_SEPARATOR = 0xfffff & pool.allocate("", "", "decimal-separator");
/* 214*/        DIGIT = 0xfffff & pool.allocate("", "", "digit");
/* 215*/        DISABLE_OUTPUT_ESCAPING = 0xfffff & pool.allocate("", "", "disable-output-escaping");
/* 216*/        DOCTYPE_PUBLIC = 0xfffff & pool.allocate("", "", "doctype-public");
/* 217*/        DOCTYPE_SYSTEM = 0xfffff & pool.allocate("", "", "doctype-system");
/* 218*/        ELEMENTS = 0xfffff & pool.allocate("", "", "elements");
/* 219*/        ENCODING = 0xfffff & pool.allocate("", "", "encoding");
/* 220*/        EXCLUDE_RESULT_PREFIXES = 0xfffff & pool.allocate("", "", "exclude-result-prefixes");
/* 222*/        EXTENSION_ELEMENT_PREFIXES = 0xfffff & pool.allocate("", "", "extension-element-prefixes");
/* 225*/        FORMAT = 0xfffff & pool.allocate("", "", "format");
/* 226*/        FROM = 0xfffff & pool.allocate("", "", "from");
/* 227*/        GROUPING_SEPARATOR = 0xfffff & pool.allocate("", "", "grouping-separator");
/* 228*/        GROUPING_SIZE = 0xfffff & pool.allocate("", "", "grouping-size");
/* 229*/        GROUP_BY = 0xfffff & pool.allocate("", "", "group-by");
/* 230*/        HANDLER = 0xfffff & pool.allocate("", "", "handler");
/* 231*/        HREF = 0xfffff & pool.allocate("", "", "href");
/* 232*/        ID = 0xfffff & pool.allocate("", "", "id");
/* 233*/        IMPLEMENTS_PREFIX = 0xfffff & pool.allocate("", "", "implements-prefix");
/* 234*/        INDENT = 0xfffff & pool.allocate("", "", "indent");
/* 235*/        INFINITY = 0xfffff & pool.allocate("", "", "infinity");
/* 236*/        LANG = 0xfffff & pool.allocate("", "", "lang");
/* 237*/        LANGUAGE = 0xfffff & pool.allocate("", "", "language");
/* 238*/        LETTER_VALUE = 0xfffff & pool.allocate("", "", "letter-value");
/* 239*/        LEVEL = 0xfffff & pool.allocate("", "", "level");
/* 240*/        MATCH = 0xfffff & pool.allocate("", "", "match");
/* 241*/        MEDIA_TYPE = 0xfffff & pool.allocate("", "", "media-type");
/* 242*/        METHOD = 0xfffff & pool.allocate("", "", "method");
/* 243*/        MINUS_SIGN = 0xfffff & pool.allocate("", "", "minus-sign");
/* 244*/        MODE = 0xfffff & pool.allocate("", "", "mode");
/* 245*/        NAME = 0xfffff & pool.allocate("", "", "name");
/* 246*/        NAMESPACE = 0xfffff & pool.allocate("", "", "namespace");
/* 247*/        NAN = 0xfffff & pool.allocate("", "", "NaN");
/* 248*/        OMIT_XML_DECLARATION = 0xfffff & pool.allocate("", "", "omit-xml-declaration");
/* 249*/        ORDER = 0xfffff & pool.allocate("", "", "order");
/* 250*/        PATTERN_SEPARATOR = 0xfffff & pool.allocate("", "", "pattern-separator");
/* 251*/        PERCENT = 0xfffff & pool.allocate("", "", "percent");
/* 252*/        PER_MILLE = 0xfffff & pool.allocate("", "", "per-mille");
/* 253*/        PRIORITY = 0xfffff & pool.allocate("", "", "priority");
/* 254*/        RESULT_PREFIX = 0xfffff & pool.allocate("", "", "result-prefix");
/* 255*/        SELECT = 0xfffff & pool.allocate("", "", "select");
/* 256*/        SRC = 0xfffff & pool.allocate("", "", "src");
/* 257*/        STANDALONE = 0xfffff & pool.allocate("", "", "standalone");
/* 258*/        STYLESHEET_PREFIX = 0xfffff & pool.allocate("", "", "stylesheet-prefix");
/* 259*/        TERMINATE = 0xfffff & pool.allocate("", "", "terminate");
/* 260*/        TEST = 0xfffff & pool.allocate("", "", "test");
/* 261*/        USE = 0xfffff & pool.allocate("", "", "use");
/* 262*/        USE_ATTRIBUTE_SETS = 0xfffff & pool.allocate("", "", "use-attribute-sets");
/* 263*/        USER_DATA = 0xfffff & pool.allocate("", "", "user-data");
/* 264*/        VALUE = 0xfffff & pool.allocate("", "", "value");
/* 265*/        VERSION = 0xfffff & pool.allocate("", "", "version");
/* 266*/        ZERO_DIGIT = 0xfffff & pool.allocate("", "", "zero-digit");
/* 268*/        SAXON_ALLOW_AVT = 0xfffff & pool.allocate("saxon", "http://icl.com/saxon", "allow-avt");
/* 269*/        SAXON_ASSIGNABLE = 0xfffff & pool.allocate("saxon", "http://icl.com/saxon", "assignable");
/* 270*/        SAXON_DISABLE_OUTPUT_ESCAPING = 0xfffff & pool.allocate("saxon", "http://icl.com/saxon", "disable-output-escaping");
/* 272*/        SAXON_INDENT_SPACES = 0xfffff & pool.allocate("saxon", "http://icl.com/saxon", "indent-spaces");
/* 273*/        SAXON_OMIT_META_TAG = 0xfffff & pool.allocate("saxon", "http://icl.com/saxon", "omit-meta-tag");
/* 275*/        SAXON_CHARACTER_REPRESENTATION = 0xfffff & pool.allocate("saxon", "http://icl.com/saxon", "character-representation");
/* 277*/        SAXON_NEXT_IN_CHAIN = 0xfffff & pool.allocate("saxon", "http://icl.com/saxon", "next-in-chain");
/* 278*/        SAXON_REQUIRE_WELL_FORMED = 0xfffff & pool.allocate("saxon", "http://icl.com/saxon", "require-well-formed");
/* 281*/        XSL_EXCLUDE_RESULT_PREFIXES = 0xfffff & pool.allocate("xsl", "http://www.w3.org/1999/XSL/Transform", "exclude-result-prefixes");
/* 283*/        XSL_EXTENSION_ELEMENT_PREFIXES = 0xfffff & pool.allocate("xsl", "http://www.w3.org/1999/XSL/Transform", "extension-element-prefixes");
/* 285*/        XSL_USE_ATTRIBUTE_SETS = 0xfffff & pool.allocate("xsl", "http://www.w3.org/1999/XSL/Transform", "use-attribute-sets");
/* 287*/        XSL_VERSION = 0xfffff & pool.allocate("xsl", "http://www.w3.org/1999/XSL/Transform", "version");
            }

            public static void main(String args[])
            {
/* 297*/        NamePool namepool = NamePool.getDefaultNamePool();
/* 298*/        namepool.generateJavaConstants();
            }
}
